### PR TITLE
XAMARIN-43636 : Linking all fields, properties and events to SfCarousel

### PR DESCRIPTION
**Pull request by shivaniramakrishnan14**
Linking all fields, properties and events to SfCarousel

### CODE REVIEW

**Comment by Choza-rajan** [comment]
rebuild

**Comment by shivaniramakrishnan14** [comment]
rebuild

**Comment by shivaniramakrishnan14** [comment]
rebuild

**Comment by shivaniramakrishnan14** [comment]
rebuild

**Pull request closed without merging**
