### PR TITLE
XAMARIN-43198-How to set ItemSource with ItemTemplate in Step Progressbar

### PR DESCRIPTION
**Pull request by Gayathri-github7**
Hi Team,

Prepared content for ItemSource with ItemTemplate in Step Progressbar in code behind. Kindly review the changes and provide your feedback.

With Regards,
Gayathri R

### CODE REVIEW

**Review by Mohanaraja — APPROVED** [review]
Changes are fine

**Review by Mohanaraja — APPROVED** [review]
Changes are fine

**Review by Mohanaraja — APPROVED** [review]
changes are fine

**Comment by Gayathri-github7** [comment]
Hi @TresWatkins ,

Can you review and approve the changes.

With Regards,
Gayathri R

**Review by carolinedolly — APPROVED** [review]

**Pull request merged**
